/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */
/**
 * representation of an ETL job
 */
export interface Job {
    /**
     * unique identifier for this job
     */
    id: string;
    /**
     * Description of the job
     */
    description?: string;
    /**
     * date created
     */
    created_at?: string;
    /**
     * Date updated
     */
    updated_at?: string;
    /**
     * List of steps. These will be run in order, where each step's output is the next step's input, unless the 'inputs' clause is specified
     */
    steps: Step[];
    [k: string]: unknown;
}
/**
 * a step executes a block of a certain type
 */
export declare class Step {
    /**
     * optional identifier. can be used to reference from another step
     */
    id?: string;
    /**
     * type of block to run
     */
    type: string;
    /**
     * An explanation about the purpose of this instance.
     */
    properties?: any;
    /**
     * optionally map an input of this block from a named reference of another block's port. use the format of <id>/<output_port>
     */
    output_schema?: Array<any>;
    trace?: boolean;
    inputs?: {
        [k: string]: string;
    };
    constructor(attr: any);
}
